---
swagger: '2.0'
info:
  title: Energy Generation
  version: 0.7.0
  license:
    name: MIT License
    url: https://github.com/angaza/nexus-embedded/blob/master/LICENSE
    x-copyright: Copyright 2020 Angaza, Inc. All rights reserved
schemes:
  - coap
consumes:
  - application/vnd.ocf+cbor
produces:
  - application/vnd.ocf+cbor
paths:
  "/ein":  # suggested URI
    get:
      description: This Resource describes the attributes associated with a
        source (such as a solar panel, AC grid, or DC microgrid) which is
        generating energy used by this device.

        This resource exposes instantaneous power measurements,
        cumulative energy measurements (watt-hours), and the type of the source
        (solar, microgrid, etc) if available.

        The minimum set of properties to implement are 'vi' and 'ai'.

        All properties of this resource are read-only.

        Adapted from OCF specs 'oic.r.energy.generation' and 'oic.r.powersource',
        as composite resources with linked lists are not currently supported.
      parameters:
      - "$ref": "#/parameters/interface"
      responses:
        '200':
          description: ''
          x-example:
            # rt, rtr, and if are not typically returned
            # (requires optional 'oic.if.baseline' support)
            rt:
            - angaza.com.nexus.channel.core.energy.generation
            rtr:
            - 102
            if:
            - oic.if.r
            st: 1  # DC solar
            ft: false  # no fault detected
            pi: 2000  # 20W
            vi: 24043  # 24.04V
            ai: 832  # 0.832A
            eg: 18.1  # 18.1Wh
            egs: 120  # started measuring eg 2 hours ago
            egp: 60  # eg is measured in 1-hour periods
            ss: 4  # values valid as of 4 seconds ago
          schema:
            "$ref": "#/definitions/Battery"
parameters:
  interface:
    in: query
    name: if
    type: string
    enum:
    - oic.if.rw
definitions:
  Battery:
    properties:
      rt:
        description: The Resource Type.
          (only reported if oic.if.baseline interface query is supported)
        items:
          enum:
          - angaza.com.nexus.channel.core.energy.generation
          maxLength: 64
          type: string
        minItems: 1
        uniqueItems: true
        readOnly: true
        type: array
      rtr:
        description: The Nexus Channel Core Resource Type Registry value.
          (only reported if oic.if.baseline interface query is supported)
        readOnly: true
        type: integer
        minimum: 102
        maximum: 102
      if:
        description: The OCF Interface set supported by this Resource.
          (only reported if oic.if.baseline interface query is supported)
        items:
          enum:
          - oic.if.rw  # oic.if.baseline optional
          type: string
        minItems: 1
        uniqueItems: true
        readOnly: true
        type: array
      st:
        description: Type of power generator.
          Possible types -
            0 = Disconnected/None
            1 = DC Solar
            2 = AC Grid/microgrid (as a source)
            3 = DC Grid/microgrid (as a source)
            4 = AC Wind power
            5 = DC Wind power
            6 = AC Hydro power
            7 = DC Hydro power
            8 = AC Petrol/Diesel Generator
            100 = Unknown
        readOnly: true
        type: integer
        enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 100
      sf:
        description: True if there is a detectable fault on the generation side
          ('source fault', such as a short).
        readOnly: true
        type: boolean
      pi:
        description: Instantaneous 'power input', in centiwatts.
        readOnly: true
        type: integer
      vi:
        description: Instantaneous 'voltage input', in millivolts.
        readOnly: true
        type: integer
      ai:
        description: Instantaneous 'current input', in centiamps.
        type: integer
      eg:
        description: |
          'Energy generated' in deciwatt-hours(Wh / 10). Computed over a time window defined by egs and egp.
        type: integer
      egs:
        description: |
          'Energy generation start'. Minutes in the past (minutes ago)
          when the reported `eg` value began accumulation.
        type: integer
      egp:
        description: |
          'Energy generation period'. Minutes since `egs` over which
          the value of `eg` was accumulated. For example, if `egs` is 60, and
          `egp` is 60, the value of `eg` represents the watt-hours generated during
          the past hour.
        type: integer
      ss:
        description: Seconds since the observed data in this resource was
          measured.
        readOnly: true
        type: integer
        format: uint

    type: object
    required:
    - vi  # millivolts from input
    - ai  # centiamps from input
