---
swagger: '2.0'
info:
  title: Energy Consumption
  version: 0.7.0
  license:
    name: Angaza Data Model License (MIT License)
    url: https://github.com/angaza/nexus-embedded/blob/master/LICENSE
    x-copyright: Copyright 2020 Angaza, Inc. All rights reserved
schemes:
  - coap
consumes:
  # Note: JSON provided to render examples using redoc, actual data transmitted
  # is `application/vnd.ocf+cbor`
  #- application/vnd.ocf+cbor
  - application/json
produces:
  #- application/vnd.ocf+cbor
  - application/json
paths:
  "/eout":  # suggested URI
    get:
      summary: Retrieve current load/output energy consumption
      description: |
        This Resource describes the attributes associated with a
        load (or loads) connected to this device consuming energy.

        If available, up to two 'sub-loads' can also be exposed to provide
        more details about the split of energy to different simultaneous
        loads.

        The minimum set of properties to implement are 'ao' and 'po'.

        All properties of this resource are read-only.

        Example `GET` response body in CBOR:

        Originally derived from from OCF specs [`oic.r.energy.generation`](https://www.oneiota.org/revisions/6172)
        and [`oic.r.energy.overload`](https://www.oneiota.org/revisions/6174)

      parameters:
      - "$ref": "#/parameters/interface"
      responses:
        '200':
          description: ''
          x-example:
            # rt, rtr, and if are not typically returned
            # (requires optional 'oic.if.baseline' support)
            rt:
            - angaza.com.nexus.channel.core.energy.consumption
            rtr:
            - 103
            if:
            - oic.if.r
            st: 1  # solar
            ft: false  # no fault detected
            po: 2000  # 20W
            vo: 24043  # 24.04V
            ao: 832  # 0.832A
            ss: 4  # values valid as of 4 seconds ago
          schema:
            "$ref": "#/definitions/Battery"
parameters:
  interface:
    in: query
    name: if
    type: string
    enum:
    - oic.if.rw
definitions:
  Battery:
    properties:
      rt:
        description: |
          **Fixed Specification Value Only**. The Resource Type
          (Only reported if `oic.if.baseline` interface query is supported)
        items:
          enum:
          - angaza.com.nexus.channel.core.energy.consumption
          maxLength: 64
          type: string
        minItems: 1
        uniqueItems: true
        readOnly: true
        type: array
      rtr:
        description: The Nexus Channel Core Resource Type Registry value.
          (only reported if oic.if.baseline interface query is supported)
        readOnly: true
        type: integer
        minimum: 102
        maximum: 102
      if:
        description: The OCF Interface set supported by this Resource.
          (only reported if oic.if.baseline interface query is supported)
        items:
          enum:
          - oic.if.rw  # oic.if.baseline optional
          type: string
        minItems: 1
        uniqueItems: true
        readOnly: true
        type: array
      po:
        description: Instantaneous total load 'power output', in centiwatts.
        readOnly: true
        type: integer
        format: uint
        example: 125
      ldt:
        description: |
          Array with one entry for each connected load type.
          Possible types -
            * 1 = Generic Load/Type Unknown
            * 5 = USB 5V Charging (Single load)
            * 6 = USB 5V Charging (Bank of phones/loads)
            * 10 = Home Lighting
            * 20 = Industrial/Work Lighting
            * 30 = Refrigeration
            * 40 = Water Pump
            * 50 = Fan
            * 60 = Radio
            * 70 = Television
            * 80 = Laptop PC
            * 90 = Desktop PC
            * 100 = Speaker Sound System (PA)
            * 110 = Textile (Sewing) Machine
            * 120 = Barber Equipment (Clippers)
        readOnly: true
        type: array
        minItems: 0
        items:
          type: integer
          enum:
            - 1
            - 5
            - 6
            - 10
            - 20
            - 30
            - 40
            - 50
            - 60
            - 70
            - 80
            - 90
            - 100
            - 110
            - 120
        example: [5, 70]
      lda:
        description: |
          Current (in )
      ft:
        description: True if there is a detectable fault for any output/load
          (such as a short).
        readOnly: true
        type: boolean
        example: false
      eo:
        description: |
          'Energy output' in deciwatt-hours(Wh / 10). Computed over a time
          window defined by `eos` and `eop`.
        type: integer
      eos:
        description: |
          'Energy output start'. Minutes in the past (minutes ago)
          when the reported `eg` value began accumulation.
        type: integer
        format: uint
        example: 120
      eop:
        description: |
          'Energy output period'. Minutes since `eos` over which
          the value of `eo` was accumulated. For example, if `eos` is 60, and
          `eop` is 60, the value of `eg` represents the watt-hours generated during
          the past hour.
        type: integer
        format: uint
        example: 60
      ss:
        description: Seconds since the observed data in this resource was
          measured.
        minimum: 0
        readOnly: true
        type: integer
        format: uint


    type: object
    required:
    - po  # millivolts from input
