---
swagger: '2.0'
info:
  title: Energy Consumption
  version: 0.7.0
  license:
    name: MIT License
    url: https://github.com/angaza/nexus-embedded/blob/master/LICENSE
    x-copyright: Copyright 2020 Angaza, Inc. All rights reserved
schemes:
  - coap
consumes:
  - application/vnd.ocf+cbor
produces:
  - application/vnd.ocf+cbor
paths:
  "/eout":  # suggested URI
    get:
      description: This Resource describes the attributes associated with a
        load (or loads) connected to this devices consuming energy.

        The property 'po' output powe
        df
         vo
         ao
         ss

        The Property 'st' (sourcetype) is an enum integer value indicating the type
        of power source. 'sf' (sourcefault) is true if there is a detectable problem
        with the power source (such as a short), false otherwise.
        'pi'  is the instantaneous power input being provided by the source in
        centiwatts. 'vi' is the current voltage of the power source in millivolts
        (RMS if AC source). 'ai' (ampinput) is the current power being supplied
        by the source, in centiamps.
        'ss' is the seconds since the measurement was sampled.

        Adapted from OCF specs 'oic.r.energy.generation' and 'oic.r.powersource',
        as composite resources with linked lists are not currently supported.
      parameters:
      - "$ref": "#/parameters/interface"
      responses:
        '200':
          description: ''
          x-example:
            # rt, rtr, and if are not typically returned
            # (requires optional 'oic.if.baseline' support)
            rt:
            - angaza.com.nexus.channel.core.energy.consumption
            rtr:
            - 103
            if:
            - oic.if.r
            st: 1  # solar
            ft: false  # no fault detected
            po: 2000  # 20W
            vi: 24043  # 24.04V
            ai: 832  # 0.832A
            ss: 4  # values valid as of 4 seconds ago
          schema:
            "$ref": "#/definitions/Battery"
parameters:
  interface:
    in: query
    name: if
    type: string
    enum:
    - oic.if.rw
definitions:
  Battery:
    properties:
      rt:
        description: The Resource Type.
          (only reported if oic.if.baseline interface query is supported)
        items:
          enum:
          - angaza.com.nexus.channel.core.powersource
          maxLength: 64
          type: string
        minItems: 1
        uniqueItems: true
        readOnly: true
        type: array
      rtr:
        description: The Nexus Channel Core Resource Type Registry value.
          (only reported if oic.if.baseline interface query is supported)
        readOnly: true
        type: integer
        minimum: 102
        maximum: 102
      if:
        description: The OCF Interface set supported by this Resource.
          (only reported if oic.if.baseline interface query is supported)
        items:
          enum:
          - oic.if.rw  # oic.if.baseline optional
          type: string
        minItems: 1
        uniqueItems: true
        readOnly: true
        type: array
      st:
        description: Type of power generator.
          Possible types -
            0 = Disconnected/None
            1 = Solar
            2 = DC Grid/microgrid (as a source only)
            3 = AC Grid/microgrid (as a source only)
            4 = Wind Turbine
            5 = Hydro Turbine
            6 = Petrol/Diesel Generator
            100 = Unknown
        readOnly: true
        type: integer
        enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 100
      df:
        description: True if there is a fault or defect on the generation side
          ('source fault', such as a short).
        readOnly: true
        type: boolean
      pi:
        description: Instantaneous 'power input', in centiwatts.
        readOnly: true
        type: integer
      vi:
        description: Instantaneous 'voltage input', in millivolts.
        readOnly: true
        type: integer
      ai:
        description: Instantaneous 'current input', in centiamps.
        type: integer
      eg:
        description: |
          'Energy generated' in Watt-hours(Wh).
        type: integer
      ep:
        description: |
          'Energy period', in minutes, over which eg is measured.
          If `eg` reports watt-hours over the last hour, `ep` has a value of 60.
        type: integer
      ss:
        description: Seconds since the observed data in this resource was
          measured.
        readOnly: true
        type: integer
        format: uint

    type: object
    required:
    - vi  # millivolts from input
    - ai  # centiamps from input
